- name: Deploy common settings
  hosts: all
  gather_facts: Yes
  become: True
  become_user: root
  roles:
    - common
    - ssh
  tags: common

- name: Create the PKI
  hosts: localhost
  connection: local
  become: False
  roles:
    - pki
  tags: pki

- name: Generate the kubeconfig files
  hosts: localhost
  connection: local
  become: False
  roles:
    - kubeconfig
  tags: kubeconfig

- name: Deploy loadbalancer
  hosts: loadbalancer
  gather_facts: Yes
  become: True
  become_user: root
  roles:
    - loadbalancer
  tags: deploy_loadbalancer

- name: Deploy etcd
  hosts: master
  gather_facts: Yes
  become: True
  become_user: root
  roles:
    - etcd
  tags: deploy_etcd

- name: Deploy kubernetes master nodes
  hosts: master
  gather_facts: Yes
  become: True
  become_user: root
  roles:
    - master
  tags: deploy_master

- name: Apply RBAC
  hosts: localhost
  connection: local
  become: False
  roles:
    - rbac
  tags: rbac

- name: Deploy kubernetes worker nodes
  hosts: worker
  gather_facts: Yes
  become: True
  become_user: root
  roles:
    - worker
  tags: deploy_worker

- name: Deploy addons
  hosts: master
  gather_facts: Yes
  become: True
  become_user: root
  roles:
    - addons
  tags: deploy_addons