---
- name: Create iptables rules directory
  file:
    path: /etc/iptables
    state: directory
  tags: iptables

- name: Update iptables rules file
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
  tags: iptables

- name: Apply iptables rules
  shell:
    iptables-restore < /etc/iptables/rules.v4
  tags: iptables

- name: Be sure iptables config be saved
  lineinfile:
    path: /etc/rc.local
    state: present
    insertbefore: '^exit 0'
    line: 'iptables-restore < /etc/iptables/rules.v4'
  tags: iptables