
- name: Generate kubeconfig file for admin user
  copy:
    content: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: {{ k8s_cluster_name }}
        cluster:
          certificate-authority-data: {{ k8s_ca_cert.certificate | b64encode }}
          server: {{ kube_apiserver_url }}
      contexts:
      - context:
          cluster: {{ k8s_cluster_name }}
          user: admin
        name: admin
      current-context: admin
      users:
      - name: admin
        user:
          client-certificate-data: {{ admin_cert.certificate | b64encode }}
          client-key-data: {{ admin_key.privatekey | b64encode }}
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
  run_once: True
  delegate_to: localhost
  become: False