- name: Generate kubeconfig file for control plane components
  set_fact:
    kube_apiserver_url: "{{ 'https://' + }}"

- name: Generate kubeconfig file for kube-controller-manager
  copy:
    content: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: {{ k8s_cluster_name }}
        cluster:
          certificate-authority-data: {{ k8s_ca_cert.certificate | b64encode }}
          server: {{ kube_apiserver_url }}
      contexts:
      - context:
          cluster: {{ k8s_cluster_name }}
          user: system:kube-controller-manager
        name: kube-controller-manager
      current-context: kube-controller-manager
      users:
      - name: system:kube-controller-manager
        user:
          client-certificate-data: {{ kube_controller_manager_cert.certificate | b64encode }}
          client-key-data: {{ kube_controller_manager_key.privatekey | b64encode }}
    dest: "{{ k8s_kubeconfig_path }}/kube-controller-manager.conf"

- name: Generate kubeconfig file for kube-scheduler
  copy:
    content: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: {{ k8s_cluster_name }}
        cluster:
          certificate-authority-data: {{ k8s_ca_cert.certificate | b64encode }}
          server: {{ kube_apiserver_url }}
      contexts:
      - context:
          cluster: {{ k8s_cluster_name }}
          user: system:kube-scheduler
        name: kube-scheduler
      current-context: kube-scheduler
      users:
      - name: system:kube-scheduler
        user:
          client-certificate-data: {{ kube_scheduler_cert.certificate | b64encode }}
          client-key-data: {{ kube_scheduler_key.privatekey | b64encode }}
    dest: "{{ k8s_kubeconfig_path }}/kube-scheduler.conf"

- name: Generate kubeconfig file for kubelet on master nodes
  copy:
    content: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: {{ k8s_cluster_name }}
        cluster:
          certificate-authority-data: {{ k8s_ca_cert.certificate | b64encode }}
          server: {{ kube_apiserver_url }}
      contexts:
      - context:
          cluster: {{ k8s_cluster_name }}
          user: system:node:{{ inventory_hostname }}
        name: kubelet
      current-context: kubelet
      users:
      - name: system:node:{{ inventory_hostname }}
        user:
          client-certificate-data: {{ kubelet_cert.certificate | b64encode }}
          client-key-data: {{ kubelet_key.privatekey | b64encode }}
    dest: "/var/lib/kubelet/kubelet.conf"