---
- name: Disable X11Forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: 'X11Forwarding no'
    backrefs: Yes
    validate: '/usr/sbin/sshd -f %s -t'

- name: Disable GSSAPIAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#GSSAPIAuthentication'
    line: 'GSSAPIAuthentication no'
    backrefs: Yes
    validate: '/usr/sbin/sshd -f %s -t'
  notify:
    - restart ssh