- name: Store front-proxy CA certificate
  copy:
    dest: "{{ k8s_pki_path }}/front-proxy-ca.crt"
    content: "{{ k8s_front_proxy_ca_cert.certificate }}"

- name: Generate front-proxy-client private key
  community.crypto.openssl_privatekey:
    path: "{{ k8s_pki_path }}/front-proxy-client.key"
  no_log: True
  register: front_proxy_client_key

- name: Generate front-proxy-client csr
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ front_proxy_client_key.filename }}"
    basic_constraints: "CA:FALSE"
    basic_constraints_critical: True
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: True
    extended_key_usage:
      - clientAuth
    common_name: "front-proxy-client"
    country_name: "{{ k8s_ssl_country }}"
    locality_name: "{{ k8s_ssl_location }}"
    organization_name: "{{ k8s_ssl_organization }}"
    organizational_unit_name: "{{ k8s_ssl_organization_unit }}"
  no_log: True
  register: front_proxy_client_csr

- name: Generate front-proxy-client certificate
  community.crypto.x509_certificate:
    path: "{{ k8s_pki_path }}/front-proxy-client.crt"
    csr_content: "{{ front_proxy_client_csr.csr }}"
    ownca_content: "{{ k8s_front_proxy_ca_cert.certificate }}"
    ownca_privatekey_content: "{{ k8s_front_proxy_ca_key.privatekey }}"
    provider: ownca
    ownca_not_after: +{{ k8s_ssl_expire_days }}
  no_log: True