- name: Create kube-scheduler configuration file
  copy:
    content: |
      apiVersion: kubescheduler.config.k8s.io/v1beta1
      kind: KubeSchedulerConfiguration
      clientConnection:
        kubeconfig: {{ k8s_kubeconfig_path }}/kube-scheduler.conf
      enableContentionProfiling: false
      enableProfiling: false
      leaderElection:
        leaderElect: true
    dest: "{{ k8s_kubeconfig_path }}/kube-scheduler.yaml"

- name: Create kube-scheduler manifest file
  template:
    src: "kube-scheduler.yaml.j2"
    dest: "/etc/kubelet.d/kube-scheduler.yaml"