- name: Create kubeconfig directory
  file:
    path: '{{ kubeconfig_dir }}'
    state: directory

- name: Generate kubeconfig file for admin
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
      --certificate-authority={{ pki_path }}/ca.pem \
      --embed-certs=true \
      --server=https://{{ apis_url }}:6443 \
      --kubeconfig={{ lookup('env', 'HOME') }}/.kube/config

    kubectl config set-credentials admin \
      --client-certificate={{ pki_k8s_path }}/admin.pem \
      --client-key={{ pki_k8s_path }}/admin-key.pem \
      --kubeconfig={{ lookup('env', 'HOME') }}/.kube/config

    kubectl config set-context admin \
      --cluster={{ cluster_name }} \
      --user=admin \
      --kubeconfig={{ lookup('env', 'HOME') }}/.kube/config

    kubectl config use-context admin --kubeconfig={{ lookup('env', 'HOME') }}/.kube/config

- name: Generate kubeconfig file for kube-controller-manager service
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
      --certificate-authority={{ pki_path }}/ca.pem \
      --embed-certs=true \
      --server=https://{{ apis_url }}:6443 \
      --kubeconfig={{ kubeconfig_dir }}/kube-controller-manager.conf

    kubectl config set-credentials system:kube-controller-manager \
      --client-certificate={{ pki_k8s_path }}/kube-controller-manager.pem \
      --client-key={{ pki_k8s_path }}/kube-controller-manager-key.pem \
      --embed-certs=true \
      --kubeconfig={{ kubeconfig_dir }}/kube-controller-manager.conf

    kubectl config set-context controller-manager \
      --cluster={{ cluster_name }} \
      --user=system:kube-controller-manager \
      --kubeconfig={{ kubeconfig_dir }}/kube-controller-manager.conf

    kubectl config use-context controller-manager --kubeconfig={{ kubeconfig_dir }}/kube-controller-manager.conf
  args:
    creates: '{{ kubeconfig_dir }}/kube-controller-manager.conf'

- name: Generate kubeconfig file for kube-scheduler service
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
      --certificate-authority={{ pki_path }}/ca.pem \
      --embed-certs=true \
      --server=https://{{ apis_url }}:6443 \
      --kubeconfig={{ kubeconfig_dir }}/kube-scheduler.conf

    kubectl config set-credentials system:kube-scheduler \
      --client-certificate={{ pki_k8s_path }}/kube-scheduler.pem \
      --client-key={{ pki_k8s_path }}/kube-scheduler-key.pem \
      --embed-certs=true \
      --kubeconfig={{ kubeconfig_dir }}/kube-scheduler.conf

    kubectl config set-context scheduler \
      --cluster={{ cluster_name }} \
      --user=system:kube-scheduler \
      --kubeconfig={{ kubeconfig_dir }}/kube-scheduler.conf

    kubectl config use-context scheduler --kubeconfig={{ kubeconfig_dir }}/kube-scheduler.conf
  args:
    creates: '{{ kubeconfig_dir }}/kube-scheduler.conf'

- name: Generate kubeconfig file for kubelet service
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
      --certificate-authority={{ pki_path }}/ca.pem \
      --embed-certs=true \
      --server=https://{{ apis_url }}:6443 \
      --kubeconfig={{ kubeconfig_dir }}/{{ item }}.conf

    kubectl config set-credentials system:node:{{ item }} \
      --client-certificate={{ pki_k8s_path }}/{{ item }}.pem \
      --client-key={{ pki_k8s_path }}/{{ item }}-key.pem \
      --embed-certs=true \
      --kubeconfig={{ kubeconfig_dir }}/{{ item }}.conf

    kubectl config set-context kubelet \
      --cluster={{ cluster_name }} \
      --user=system:node:{{ item }} \
      --kubeconfig={{ kubeconfig_dir }}/{{ item }}.conf

    kubectl config use-context kubelet --kubeconfig={{ kubeconfig_dir }}/{{ item }}.conf
  args:
    creates: '{{ kubeconfig_dir }}/{{ item }}.conf'
  loop: "{{ groups['worker'] }}"

- name: Be sure kubeconfig file is accessable
  file:
    path: '{{ kubeconfig_dir }}'
    state: directory
    recurse: Yes
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"