---
- name: Install OpenVPN from repository
  include: install.yml
  tags:
    - openvpn_install

- name: Configure OpenVPN
  include: configure.yml
  tags:
    - openvpn_configure

- name: Create OpenVPN clients certificate file
  include: clients.yml
  tags:
    - openvpn_clients