- name: Generate encryption secret
  set_fact:
    encryption_secret: "{{ lookup('community.general.random_string', special=False, length=32) | b64encode }}"
  no_log: True
  run_once: True

- name: Create encryption config for kubernetes apiserver
  copy:
    content: |
      apiVersion: v1
      kind: EncryptionConfig
      resources:
        - resources:
            - secrets
          providers:
            - secretbox:
                keys:
                  - name: key1
                    secret: "{{ encryption_secret }}"
            - identity: {}
    dest: "{{ k8s_kubeconfig_path }}/encryption.yaml"

- name: Create audit config for kubernetes apiserver
  copy:
    content: |
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
      - level: Metadata
    dest: "{{ k8s_kubeconfig_path }}/audit.yaml"

- name: Create kube-apiserver manifest file
  template:
    src: "kube-apiserver.yaml.j2"
    dest: "/etc/kubelet.d/kube-apiserver.yaml"